### ISSUE TITLE
Value error when running

### ISSUE THREAD

**Issue by erramuzpe** [uw-biomedical-ml/irf-segmenter#3]
I've got an error when trying to run the example command:

`python3.6 run.py example.png output.png`

I've got:

`ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3
	From merging shape 0 with other shapes. for 'tower_0/concat/concat_dim' (op: 'Pack') with input shapes: [1], [3].`

from

`File "run.py", line 51, in get_slice
    size = tf.concat(0, [ shape[:1] // parts, shape[1:] ])`

Any ideas?

thanks!
asier

**Comment by ayl** [comment]
Are you still having this error after I merged your pull request?

**Comment by erramuzpe** [comment]
@ayl apologies for the late reply... yes, I'm still getting the error :/

**Comment by ayl** [comment]
@erramuzpe I updated the requirements to the version of keras and tf that we were using when we developed this project. I believe the error messages you were getting were related to this. Could you try again with the updated requirements.txt ?

**Comment by erramuzpe** [comment]
Yes, it works! :+1:

2017-09-07 10:18 GMT-07:00 ayl <notifications@github.com>:
